# Generated by Django 2.1.7 on 2019-03-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTelegramm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('domain', models.CharField(blank=True, max_length=150, null=True, verbose_name='Доменное имя')),
                ('login', models.CharField(blank=True, max_length=150, null=True, verbose_name='Логин в telegramm')),
            ],
        ),
    ]
