# Generated by Django 2.1.7 on 2019-03-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttelegramm',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='clienttelegramm',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='clienttelegramm',
            name='domain',
            field=models.CharField(blank=True, help_text='Без знаков http:// и слэшей в конце!', max_length=150, null=True, verbose_name='Доменное имя'),
        ),
    ]
