# Generated by Django 2.1.7 on 2019-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm', '0002_auto_20190312_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttelegramm',
            name='chat_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Чат ID'),
        ),
    ]
