# Generated by Django 2.1.7 on 2019-03-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm', '0003_clienttelegramm_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttelegramm',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
