# Generated by Django 2.1.7 on 2019-03-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm', '0006_clienttelegramm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttelegramm',
            name='trello_board_name',
            field=models.CharField(default='', max_length=250, verbose_name='Trello board'),
        ),
    ]
