# Generated by Django 2.1.7 on 2019-03-27 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegramm', '0008_auto_20190321_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttelegramm',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
