# Generated by Django 2.1.7 on 2019-02-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('name_slug', models.CharField(max_length=150, verbose_name='Алиас')),
                ('meta_title', models.CharField(max_length=150, verbose_name='Мета-заголовок')),
                ('meta_keywords', models.CharField(max_length=250, verbose_name='Мета-словосочитания')),
                ('meta_description', models.CharField(max_length=250, verbose_name='Мета-описание')),
            ],
        ),
    ]
