# Generated by Django 2.1.7 on 2019-02-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=150, verbose_name='Псевдоним')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
        ),
    ]
