# Generated by Django 2.1.7 on 2019-03-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('value', models.TextField(verbose_name='Содержимое')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано?')),
            ],
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
