# Generated by Django 2.1.7 on 2019-03-06 14:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190306_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digest',
            name='value',
        ),
        migrations.AddField(
            model_name='digest',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
