# Generated by Django 2.1.7 on 2019-03-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190306_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='digest',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новый?'),
        ),
    ]
