# Generated by Django 2.1.7 on 2019-03-21 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('worksection', '0007_auto_20190225_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(db_index=True, max_length=150, unique=True)),
                ('trello_project_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='ID доски в trello')),
                ('trello_key', models.CharField(blank=True, max_length=250, null=True, verbose_name='ключ в trello')),
                ('trello_token', models.CharField(blank=True, max_length=250, null=True, verbose_name='токен в trello')),
                ('contact_email', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_telegramm', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('key', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('is_new', models.BooleanField(default=False, verbose_name='новые задачи')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.IntegerField(choices=[(0, 'Customer'), (1, 'Admin')], default=0, null=True)),
                ('w_mda', models.CharField(blank=True, max_length=200, null=True)),
                ('w_uid', models.CharField(blank=True, max_length=200, null=True)),
                ('w_login', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('w_password', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('is_support', models.BooleanField(default=False, verbose_name='суппорт')),
                ('telegram_room', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('telegram_login', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('sign', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='wproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worksection.WProject'),
        ),
    ]
