# Generated by Django 2.1.7 on 2019-03-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sign',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
