# Generated by Django 2.1.7 on 2019-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_client_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('telegram', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
    ]
