# Generated by Django 2.1.7 on 2019-03-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_client2user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='template',
            field=models.CharField(blank=True, default='locotrade', max_length=100, null=True),
        ),
    ]
