# Generated by Django 2.1.7 on 2019-03-27 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_client_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preaccount',
            name='source',
        ),
        migrations.AddField(
            model_name='preaccount',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Client'),
        ),
    ]
