# Generated by Django 2.1.7 on 2019-03-27 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_auto_20190327_1418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client2user',
            unique_together={('user', 'client')},
        ),
    ]
