# Generated by Django 2.1.7 on 2019-03-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190327_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_room',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='w_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='w_mda',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='w_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='w_uid',
        ),
        migrations.AddField(
            model_name='profile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Client'),
        ),
    ]
