# Generated by Django 2.1.7 on 2019-02-25 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worksection', '0002_wuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wproject',
            name='uid',
        ),
        migrations.AddField(
            model_name='wproject',
            name='page',
            field=models.CharField(default='', max_length=250, verbose_name='Страница в системе worksection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wproject',
            name='status',
            field=models.CharField(default='', max_length=50, verbose_name='Статус в системе worksection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wproject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
