# Generated by Django 2.1.7 on 2019-02-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksection', '0003_auto_20190225_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wuser',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='wuser',
            name='user',
        ),
        migrations.AddField(
            model_name='wuser',
            name='email',
            field=models.CharField(default='', max_length=250, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wuser',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wuser',
            name='projects',
            field=models.ManyToManyField(to='worksection.WProject'),
        ),
    ]
