# Generated by Django 2.1.7 on 2019-02-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksection', '0004_auto_20190225_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wproject',
            name='page',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Страница в системе worksection'),
        ),
        migrations.AlterField(
            model_name='wuser',
            name='email',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Email'),
        ),
    ]
