# Generated by Django 2.1.7 on 2019-02-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksection', '0005_auto_20190225_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wuser',
            name='email',
            field=models.CharField(db_index=True, max_length=250, unique=True, verbose_name='Email'),
        ),
    ]
