# Generated by Django 2.1.7 on 2019-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190328_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('inprocess', 'В работе'), ('done', 'Выполнен')], default='new', max_length=100, verbose_name='Статус'),
        ),
    ]
