# Generated by Django 2.1.7 on 2019-03-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190328_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ws_link',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='WS link'),
        ),
    ]
